[package]
name = "rush"
version = "0.1.0"
edition = "2021"

[dependencies]
glfw = "0.58.0"
gl = "0.14.0"
gl_loader = "0.1.2"
freetype = "0.7.2"
nalgebra-glm = "0.19.0"
nix = { version = "0.29.0", features = ["term", "process"] }
